// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZiU3AGFwPwK0wfwzrjOLOHknK0P0AgsM',
    appId: '1:350668006995:web:910ee343c580e3256688a6',
    messagingSenderId: '350668006995',
    projectId: 'mynotesback',
    authDomain: 'mynotesback.firebaseapp.com',
    storageBucket: 'mynotesback.appspot.com',
    measurementId: 'G-PLKM0VG1NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLHgHShUknyIi0rIVnpX99ky5a_5eXPQ',
    appId: '1:350668006995:android:9961e3c61bea75196688a6',
    messagingSenderId: '350668006995',
    projectId: 'mynotesback',
    storageBucket: 'mynotesback.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RQ6Xc2cf4xUUrtENmYIs1WoevJWySCo',
    appId: '1:350668006995:ios:f14cf10f934e09f06688a6',
    messagingSenderId: '350668006995',
    projectId: 'mynotesback',
    storageBucket: 'mynotesback.appspot.com',
    iosClientId: '350668006995-sf44ei856n3nlcdu6bhipskol49geod0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RQ6Xc2cf4xUUrtENmYIs1WoevJWySCo',
    appId: '1:350668006995:ios:f14cf10f934e09f06688a6',
    messagingSenderId: '350668006995',
    projectId: 'mynotesback',
    storageBucket: 'mynotesback.appspot.com',
    iosClientId: '350668006995-sf44ei856n3nlcdu6bhipskol49geod0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
